### ISSUE TITLE
Performance comparsion with aiofiles

### ISSUE THREAD

**Issue by diogommartins** [mosquito/aiofile#16]
I'm [considering using aiofile](https://github.com/B2W-BIT/aiologger/issues/16) for the FileHandler implementation of [aiologger](https://github.com/B2W-BIT/aiologger). Could you help me with the pros and cons comparing aiofile with [aiofiles](https://github.com/Tinche/aiofiles) threadpool implementation ?

**Comment by mosquito** [comment]
@daltonmatos the Linux aio.h implementation uses thread pool under the hood. You could read complete explanation here https://stackoverflow.com/a/8782305.

The [mosquito/aiofile](https://github.com/mosquito/aiofile) has aio.h binding. And so it turns out that it works with internal system thread pool. 
The main advantage it's a this implementation is that it releases the GIL. It's reasonable if you try to run many event-loop instances in the different threads.

On [my tests](https://gist.github.com/mosquito/673a85c0be48af2ee2d382aaa0c1e3f0#file-results-md), I don't see the performance increase. Moreover when the chunks are small this is slower than thread-pool implementation.

IMHO: The one better thing is [aio_fsync](https://www.systutorials.com/docs/linux/man/3-aio_fsync/). It's a real do syncing file to the filesystem and on my experiments with raspberry pi after call aio_fsync a file was really stored on SD-card.

By the way, I will be experimenting with libaio (not aio.h), but not yet.

**Comment by daltonmatos** [comment]
Thanks @mosquito for your response.

@diogommartins, do you think this issue could be closed?

Thanks.

**Comment by diogommartins** [comment]
Thanks a lot, @mosquito  !
