### ISSUE TITLE
Infinite reading from a file

### ISSUE THREAD

**Issue by k-zaytsev** [mosquito/aiofile#48]
https://github.com/ICRAR/ijson/issues/38

```python
import asyncio

from aiofile import AIOFile

data = b'hi'

async def main():
    with open("test.data", "wb") as fp:
        fp.write(data)
    async with AIOFile("test.data", "rb") as fp:
        while True:
            buf = await fp.read(2)
            if not buf:
                break
            print(buf)

asyncio.run(main())
```

**Comment by mosquito** [comment]
It's missuse of aiofile cause the `AIOFile` object expects the offset argument (so it's zero by default 😀). For linear-like file reading you have to use [`Reader`](https://github.com/mosquito/aiofile#write-and-read-with-helpers) helper. 

The reason is the aiofile is a library to made real asyncronous file operations. Asyncronous API with builtin file position pointer doesn't known to me. So for user this abstracitons will be provided as addidional utilities.

Please double check the aiofile README, it contains a solution.
